---
jupyter:
  jupytext:
    metadata_filter:
      notebook:
        additional: all
        excluded:
        - language_info
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.0'
      jupytext_version: 0.8.6
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

Data from [2018 Behavioral Risk Factor Surveillance System survey](Ahttps://www.cdc.gov/brfss/annual_data/annual_2018.html).

The raw data are fairly large - about 100M zip compressed, and nearly 1G when uncompressed.

Data from the [SAS transport format download[(https://www.cdc.gov/brfss/annual_data/2018/files/LLCP2018XPT.zip).

Variable list in the [code book](https://www.cdc.gov/brfss/annual_data/2018/pdf/codebook18_llcp-v2-508.pdf).

```{python}
import os
import os.path as op
import urllib.request
from zipfile import ZipFile
```

```{python}
# Fetch data file from URL.
brfss_url = 'https://www.cdc.gov/brfss/annual_data/2018/files/LLCP2018XPT.zip'
zfname, msg = urllib.request.urlretrieve(brfss_url, 'LLCP2018XPT.zip')
```

```{python}
# Get data file.
with ZipFile(zfname) as zf:
    zf.extract('LLCP2018.XPT ')
# Remove trailing space in file extension in order for Pandas to recognize
# the `.xpt` extension as SAS transport format.
os.rename('LLCP2018.XPT ', 'LLCP2018.xpt')
```

```{python}
import numpy as np
import pandas as pd
```

```{python}
df = pd.read_sas('LLCP2018.xpt')
df.head()
```

There are about half a million rows, and several hundred columns.

```{python}
df.shape
```

`_STATE` is [State FIPS Code](https://en.wikipedia.org/wiki/Federal_Information_Processing_Standard_state_code).

```{python}
state_fips = df['_STATE'].astype(int)
state_fips.value_counts(sort=False)
```

Replace with two-letter postal abbreviation:

```{python}
us_states = pd.read_csv(op.join('..', 'us_states', 'us_states.csv'))
us_states.head()
```

```{python}
# Make a Series to look up state abbreviations from FIPs codes.
lookup = us_states['post_code']
lookup.index = us_states['fips']
lookup.head()
```

```{python}
state_fips.head()
```

```{python}
# Look up abbreviations from FIPS code.
state_pcs = lookup.loc[state_fips]
# Set original index.
state_pcs.index = state_fips.index
state_pcs.value_counts(sort=False)
```

`HTM4` is the "Computed Height in Meters", with 2 implied decimal places, so in fact it is the computed height in centimeters.

It is computed because the original variable, `HEIGHT3` could be in feet / inches or meters.

```{python}
height_cm = df['HTM4']
height_cm.head()
```

```{python}
# Heights are all integers.
good_height = height_cm.dropna()
np.all(good_height == np.round(good_height))
```

`WTKG3` is "Computed Weight in Kilograms".  It has 2 implied decimal places, so it is in units of 10 grams.  It is computed from the mixed unit `WEIGHT2` variable.

```{python}
weight_kg = df['WTKG3'] / 100
weight_kg.head()
```

`GENHLTH` is "General Health":

* 1 Excellent
* 2 Very good
* 3 Good
* 4 Fair
* 5 Poor
* 7 Don’t know/Not Sure
* 9 Refused
* BLANK Not asked or Missing

```{python}
genhlth = df['GENHLTH']
genhlth.value_counts()
```

```{python}
def recode_7_9(val):
    if val in (7, 9):
        return np.nan
    return val
```

```{python}
genhlth_clean = genhlth.apply(recode_7_9)
genhlth_clean.value_counts()
```

`PHYSHLTH`: "Number of Days Physical Health Not Good"; "Now thinking about your physical health, which includes physical illness and injury, for how many days during the past 30 days was your physical health not good?".

* 1 - 30 Number of days
* 88 None
* 77 Don’t know/Not sure
* 99 Refused
* BLANK Not asked or Missing

```{python}
physhlth = df['PHYSHLTH']
physhlth.describe()
```

```{python}
def recode_88_77_99(val):
    if val == 88:
        return 0
    if val in (77, 99):
        return np.nan
    return val
```

```{python}
physhlth_clean = physhlth.apply(recode_88_77_99)
physhlth_clean.describe()
```

`MENTHLTH`: "Number of Days Mental Health Not Good" ; "Now thinking about your mental health, which includes stress, depression, and problems with emotions, for how many days during the past 30 days was your mental health not good?".

* 1 - 30 Number of days
* 88 None
* 77 Don’t know/Not sure
* 99 Refused
* BLANK Not asked or Missing

```{python}
menhlth = df['MENTHLTH']
menhlth.describe()
```

```{python}
menhlth_clean = menhlth.apply(recode_88_77_99)
menhlth_clean.describe()
```

`SLEPTIM1`: "How Much Time Do You Sleep" ; "On average, how many hours of sleep do you get in a 24-hour period?"

* 1 - 24 Number of hours
* 77 Don’t know/Not sure
* 99 Refused
* BLANK Missing

```{python}
hrs_sleep = df['SLEPTIM1']
hrs_sleep.describe()
```

```{python}
hrs_sleep_clean = hrs_sleep.apply(recode_88_77_99)
hrs_sleep_clean.describe()
```

`SEX1` : "Respondents Sex" ; "What is your sex? or What was your sex at birth? Was it..."

* 1 Male
* 2 Female
* 7 Don't know/Not Sure
* 9 Refused

```{python}
sex = df['SEX1']
sex.value_counts()
```

```{python}
sex_clean = sex.apply(recode_7_9)
sex_clean.value_counts()
```

```{python}
sex_labels = sex_clean.astype(object)
sex_labels[sex_clean == 1] = 'M'
sex_labels[sex_clean == 2] = 'F'
sex_labels.value_counts()
```

`SMOKE100` : "Smoked at Least 100 Cigarettes" ; "Have you smoked at least 100 cigarettes in your entire life?"

* 1 Yes
* 2 No
* 7 Don't know/Not Sure
* 9 Refused
* BLANK Not asked or Missing

```{python}
smoke100 = df['SMOKE100']
smoke100.value_counts()
```

```{python}
smoke100_clean = smoke100.apply(recode_7_9)
smoke100_clean.value_counts()
```

```{python}
smoke100_labels = smoke100_clean.astype(object)
smoke100_labels[smoke100_clean == 1] = True
smoke100_labels[smoke100_clean == 2] = False
smoke100_labels.value_counts()
```

```{python}
clean_df = pd.DataFrame()
cols = [state_pcs, height_cm, weight_kg, sex_clean,
         genhlth_clean, physhlth_clean,
         menhlth_clean, smoke100_clean]
names = ['state', 'height_cm', 'weight_kg',
         'gen_health', 'phys_health_days', 'mental_health_days',
          'smoke100']
for col, name in zip(cols, names):
    clean_df[name] = col
clean_df.head()
```

```{python}
out_fname = op.join('processed', 'brfss_vars.csv')
clean_df.to_csv(out_fname, index=False)
pd.read_csv(out_fname).head()
```
